language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false
dist: xenial

before_script:    
    - COMPOSER_MEMORY_LIMIT=-1 composer install

script:
    - vendor/bin/phpunit --stderr --verbose

notifications:
  email: philipp.braeutigam@googlemail.com
